# Generated by Django 5.1.1 on 2024-09-24 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Hashtags',
                'ordering': ['hashtag'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('stayed_for', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('City', models.ManyToManyField(to='viewer.city')),
                ('country', models.ManyToManyField(to='viewer.country')),
                ('hashtag', models.ManyToManyField(blank=True, to='viewer.hashtag')),
                ('transport', models.ManyToManyField(to='viewer.transport')),
                ('weather', models.ManyToManyField(to='viewer.weather')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ['arrival_date'],
            },
        ),
    ]
