# Generated by Django 5.1.1 on 2024-10-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='transport',
            field=models.ManyToManyField(blank=True, to='viewer.transport'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='weather',
            field=models.ManyToManyField(blank=True, to='viewer.weather'),
        ),
    ]
